
#服务调用方
#服务中心eureka服务调用
#整合了feign
#加上了feign hystrix

server:
  port: 9104
spring:
  application:
    name: springcloud-eureka-consumer
eureka:
  instance:
    # 使用 ip 代替实例名
    prefer-ip-address: true
    # 实例的主机名
    hostname: ${spring.cloud.client.ip-address}
    # 实例的 ID 规则
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    serviceUrl:
      # 注册中心地址
      defaultZone: http://eurekaservice1:8761/eureka/,http://eurekaservice2:8762/eureka/,http://eurekaservice3:8763/eureka/,http://eurekaservice4:8764/eureka/
feign:
  circuitbreaker:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
