# 端口
server:
  port: 8761

# 应用名称
spring:
  application:
    name: register-server

eureka:
  instance:
    # 使用 ip 代替实例名
    prefer-ip-address: true
    # 实例的主机名
    hostname: eurekaservice1
    # 实例的 ID 规则
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    # 是否向注册中心注册自己
    registerWithEureka: true
    # 是否向注册中心获取注册信息
    fetchRegistry: true
    service-url:
      # 注册中心地址
      defaultZone: http://eurekaservice2:8762/eureka/,http://eurekaservice3:8763/eureka/,http://eurekaservice4:8764/eureka/
  #设置改参数值为false，以确保注册中心将不可用的实例删除
  server:
    #注册中心的保护机制
    enable-self-preservation: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always