
server:
  port: 9102
spring:
  application:
    name: bootadmin-client
#  boot:
#    admin:
#      client:
#        url: http://127.0.0.1:9101
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
logging:
  file:
    name: admin-client.log



eureka:
  instance:
    # 使用 ip 代替实例名
    prefer-ip-address: true
    # 实例的主机名
    hostname: ${spring.cloud.client.ip-address}
    # 实例的 ID 规则
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    serviceUrl:
      # 注册中心地址
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always