# 端口
server:
  port: 9000

# 应用名称
spring:
  application:
    name: eurake-client
  #  data:
  #    elasticsearch:
  #      cluster-name: elasticsearch # es集群的名称
  #        cluster-nodes: 127.0.0.1:9200 # es的连接地址及端口号
  #      repositories:
  #        enabled: true
  #  Jackson:
  #    default-property-inclusion: non_null  # 返回的结果是null的就排除
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/sis_zzsy?serverTimezone=GMT%2B8
#    username: root
#    password: root123456
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  ##默认密码为空
#  redis:
#    host: 127.0.0.1
#    # Redis服务器连接端口
#    port: 6379
#    #默认是索引为0的数据库
#    database: 8
#    jedis:
#      pool:
#        #连接池最大连接数（使用负值表示没有限制）
#        max-active: 100
#        # 连接池中的最小空闲连接
#        max-idle: 10
#        # 连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-wait: 100000
#        # 连接超时时间（毫秒）
#        timeout: 5000
#
#
##
eureka:
  instance:
    # 使用 ip 代替实例名
    prefer-ip-address: true
    # 实例的主机名
    hostname: ${spring.cloud.client.ip-address}
    # 实例的 ID 规则
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    serviceUrl:
      # 注册中心地址
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/