# 端口
server:
  port: 9003

# 应用名称
spring:
  application:
    name: webservice-server
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/person?serverTimezone=GMT%2B8
    username: root
    password: root123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    #对于rabbitMQ的支持
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
logging:
  level:
    com.penghy.server.mapper: debug




eureka:
  instance:
    # 使用 ip 代替实例名
    prefer-ip-address: true
    # 实例的主机名
    hostname: ${spring.cloud.client.ip-address}
    # 实例的 ID 规则
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    serviceUrl:
      # 注册中心地址
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/